from app.db.models import CaseSummary, Case, Entity, EntityLink, EvidenceFile, RiskLevel, UploadStatus
from app.services.ai.case_summary import generate_case_summary
from app.services.reports.pdf_generator import load_known_apk_hashes, load_known_bad_urls
from .base import AgentContext, AgentDefinition, BaseAgent, Recorder


def _etype(e: Entity) -> str:
    return e.entity_type.value if hasattr(e.entity_type, "value") else str(e.entity_type)


class InvestigationReportAgent(BaseAgent):
    definition = AgentDefinition(
        id="investigation_report",
        name="Investigation Report Agent",
        role="Checks report readiness and prepares the narrative and action plan",
        description=(
            "Checks that the case is ready for court-facing reports, prepares the case narrative, and recommends which "
            "reports to issue (Investigative Brief, Takedown Notice). Encrypted PDFs are still generated by the officer."
        ),
        category="reporting",
        access="updates_case",
        outputs=["Readiness score", "Case narrative", "Report plan", "Freeze/takedown targets"],
    )

    def run(self, ctx: AgentContext, rec: Recorder) -> str:
        db = ctx.db
        case = db.query(Case).filter(Case.id == ctx.case_id).first()
        files = db.query(EvidenceFile).filter(EvidenceFile.case_id == ctx.case_id).all()
        entities = db.query(Entity).filter(Entity.case_id == ctx.case_id).all()
        links = db.query(EntityLink).filter(EntityLink.case_id == ctx.case_id).count()

        with rec.step("Check report readiness") as s:
            checks = [
                ("Evidence uploaded", len(files) > 0),
                ("Evidence processed", bool(files) and all(f.upload_status == UploadStatus.processed for f in files)),
                ("Entities extracted", len(entities) > 0),
                ("Correlation links established", links > 0),
                ("Risk scored", case.risk_score is not None),
            ]
            passed = sum(1 for _, ok in checks if ok)
            readiness = round(100 * passed / len(checks))
            s.detail = f"{passed}/{len(checks)} checks passed ({readiness}% ready)"
            if passed < len(checks):
                s.status = "warn"
            rec.data["checklist"] = [{"check": c, "passed": ok} for c, ok in checks]
        rec.metrics["readiness"] = readiness
        for c, ok in checks:
            if not ok:
                rec.finding("medium", f"Not ready: {c}", "")
        if readiness < 100:
            rec.recommend("Complete the failed readiness checks (or run the Case Orchestrator) before issuing court-facing reports.")

        with rec.step("Prepare case narrative") as s:
            latest = (
                db.query(CaseSummary).filter(CaseSummary.case_id == ctx.case_id).order_by(CaseSummary.generated_at.desc()).first()
            )
            if entities and (latest is None or ctx.options.get("refresh_narrative")):
                latest = generate_case_summary(ctx.case_id, db)
                s.detail = "Narrative generated from the current graph"
            elif latest:
                s.detail = "Existing narrative reused"
            else:
                s.status = "skipped"
                s.detail = "No entities to summarise"
            rec.metrics["narrative_ready"] = latest is not None

        with rec.step("Plan reports and directives") as s:
            freeze = sorted({e.value for e in entities if _etype(e) in ("upi_handle", "account") and e.risk_level == RiskLevel.high})
            bad_urls = [b["url"].strip().lower() for b in load_known_bad_urls()]
            bad_hashes = {b["sha256"] for b in load_known_apk_hashes()}
            url_hit = any(_etype(e) == "url" and any(e.value.strip().lower() in b or b in e.value.strip().lower() for b in bad_urls) for e in entities)
            apk_hit = any((f.sha256_hash or "").lower() in bad_hashes for f in files)
            takedown = url_hit or apk_hit or any(_etype(e) == "url" and e.risk_level == RiskLevel.high for e in entities)
            plan = [
                {
                    "report": "Investigative Brief Dossier",
                    "legal_basis": "Section 65B Indian Evidence Act",
                    "recommended": readiness >= 60,
                    "reason": f"{len(freeze)} freeze target(s) identified" if freeze else "Summarises evidence, links and timeline",
                },
                {
                    "report": "Statutory Takedown Notice",
                    "legal_basis": "Section 69A IT Act",
                    "recommended": bool(takedown),
                    "reason": "Malicious infrastructure identified" if takedown else "No malicious URLs or APKs identified",
                },
            ]
            rec.data.update({"report_plan": plan, "freeze_targets": freeze[:10]})
            s.detail = "Recommended: " + (", ".join(p["report"] for p in plan if p["recommended"]) or "none yet")
        if freeze:
            rec.recommend(f"Include {len(freeze)} high-risk account/UPI handle(s) as Section 91 CrPC freeze targets in the brief.")
        if any(p["recommended"] for p in plan):
            rec.recommend("Open Investigative Reports to generate the encrypted PDF(s); you will confirm your officer password.")
        rec.metrics.update({"freeze_targets": len(freeze), "takedown_recommended": bool(takedown)})
        return f"Report readiness {readiness}%; " + (
            "recommended: " + ", ".join(p["report"] for p in plan if p["recommended"]) if any(p["recommended"] for p in plan) else "no report recommended yet"
        ) + "."
