import React, { useMemo, useState } from "react";
import { Layers, RotateCcw, ZoomIn, ZoomOut } from "lucide-react";

export const formatEntityType = (type) => ({ upi_handle: "UPI handle", account: "Bank account", phone: "Phone", imei: "Device", imsi: "SIM", ip_address: "IP address", apk_hash: "APK", url: "URL" }[type] || "Entity");
export const formatBasis = (basis) => ({ shared_upi_handle: "shares UPI", shared_account: "shares account", shared_imei: "same device", shared_ip: "same IP", shared_subnet: "same subnet", shared_phone: "same phone" }[basis] || (basis || "linked"));
const palette = { phone: "#60a5fa", imsi: "#60a5fa", imei: "#c084fc", account: "#fbbf24", upi_handle: "#fbbf24", ip_address: "#4ade80", url: "#38bdf8" };

export default function NetworkGraph({ nodes = [], edges = [], isLoading }) {
  const [zoom, setZoom] = useState(1);
  const [selected, setSelected] = useState(null);
  const positions = useMemo(() => {
    const result = {}; const ranked = [...nodes].sort((a, b) => String(a.id).localeCompare(String(b.id)));
    ranked.forEach((node, i) => { const angle = -Math.PI / 2 + i * (2 * Math.PI / Math.max(ranked.length, 1)); const radius = i ? 210 : 0; result[node.id] = { x: 480 + Math.cos(angle) * radius, y: 310 + Math.sin(angle) * radius }; });
    return result;
  }, [nodes]);
  if (isLoading && !nodes.length) return <div className="flex h-[620px] items-center justify-center rounded-xl border border-border bg-bg"><div className="text-center"><div className="mx-auto mb-3 h-8 w-8 animate-spin rounded-full border-2 border-accent/30 border-t-accent" /><p className="font-medium text-text">Building your relationship map…</p><p className="mt-1 text-xs text-textFaint">Analyzing connections…</p></div></div>;
  if (!nodes.length) return <div className="flex h-[620px] flex-col items-center justify-center rounded-xl border border-border bg-bg"><Layers className="mb-3 h-8 w-8 text-textFaint" /><p className="font-medium text-text">No entity connections generated</p></div>;
  return <div className="relative flex h-[620px] flex-col overflow-hidden rounded-xl border border-border bg-bg"><div className="flex items-center justify-between border-b border-border p-3"><div><b className="text-sm text-text">Relationship map</b><p className="text-[11px] text-textFaint">{nodes.length} entities · {edges.length} links · drag-free bounded viewport</p></div><div className="flex gap-1"><button onClick={() => setZoom(z => Math.max(.65, z - .15))} className="p-2 text-textDim"><ZoomOut className="h-4 w-4" /></button><button onClick={() => setZoom(z => Math.min(2, z + .15))} className="p-2 text-textDim"><ZoomIn className="h-4 w-4" /></button><button onClick={() => setZoom(1)} className="p-2 text-textDim"><RotateCcw className="h-4 w-4" /></button></div></div><div className="relative min-h-0 flex-1 overflow-hidden bg-[radial-gradient(ellipse_at_center,rgba(14,116,144,.16),transparent_55%),#020617]"><svg viewBox="0 0 960 620" className="h-full w-full"><g transform={`translate(480 310) scale(${zoom}) translate(-480 -310)`}>{edges.map(edge => { const a = positions[edge.source], b = positions[edge.target]; if (!a || !b) return null; return <g key={edge.id || `${edge.source}-${edge.target}`}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={edge.extra?.cross_case ? "#fb7185" : "#38bdf8"} strokeWidth="1.6" strokeDasharray={edge.extra?.cross_case ? "6 5" : ""} /><text x={(a.x+b.x)/2} y={(a.y+b.y)/2-7} textAnchor="middle" fill="#cbd5e1" fontSize="9">{formatBasis(edge.basis)}</text></g>; })}{nodes.map(node => { const p = positions[node.id], color = node.risk_level === "high" ? "#fb7185" : palette[node.entity_type] || "#22d3ee"; return <g key={node.id} transform={`translate(${p.x},${p.y})`} onClick={() => setSelected(node)} className="cursor-pointer"><circle r="31" fill="#081728" stroke={color} strokeWidth="2.5" /><text y="6" textAnchor="middle" fill={color} fontSize="20">●</text><text y="51" textAnchor="middle" fill="#e2e8f0" fontSize="11">{String(node.label || "Unknown").slice(0, 18)}</text><text y="66" textAnchor="middle" fill="#94a3b8" fontSize="9">{formatEntityType(node.entity_type)}</text></g>; })}</g></svg>{selected && <div className="absolute right-4 top-4 w-72 rounded-xl border border-border bg-bg p-4 shadow-xl"><button onClick={() => setSelected(null)} className="float-right text-textDim">×</button><p className="text-[10px] font-bold uppercase text-accent">Selected entity</p><p className="mt-2 break-all font-mono text-sm font-bold text-text">{selected.label}</p><p className="mt-3 text-xs text-textDim">{selected.anomaly_reason || "Part of the evidence relationship trail."}</p></div>}</div></div>;
}

