/**
 * Standard Mode (official portal skin) — configurable identity and copy.
 *
 * Provides a complete English and Hindi localization system across all
 * Standard Mode components, pages, modals, forms, error states, and the AI chatbot.
 */

export const PORTAL = {
  // ── Portal naming ──────────────────────────────────────────────────────
  portalName: "TraceX",
  portalTitle: {
    en: "Cyber Fraud Case Management & Correlation System",
    hi: "साइबर धोखाधड़ी प्रकरण प्रबंधन एवं सहसंबंध प्रणाली",
  },

  // Brand mark (lightweight derivative of /icon.png, served from /public).
  logoSrc: "/icon-192.png",

  // ── Optional contact details (rendered in the footer only when provided) ─
  officeAddress: null, // e.g. "Cyber Cell HQ, Bhopal, Madhya Pradesh – 462001"
  helpdesk: null, // e.g. "0755-XXXXXXX · helpdesk@example.gov.in"
};

/** Complete UI dictionaries supporting English / Hindi language toggle */
export const STRINGS = {
  en: {
    // ── Shell, Navigation & Utility ──────────────────────────────────────
    skip: "Skip to main content",
    textSize: "Text size",
    textSizeDecrease: "Decrease text size",
    textSizeDefault: "Default text size",
    textSizeIncrease: "Increase text size",
    contrast: "High contrast",
    displayMode: "Display mode",
    standard: "Standard",
    analysis: "Analysis",
    language: "Language",
    dashboard: "Dashboard",
    correlation: "Correlation & Graph",
    reports: "Reports",
    agents: "AI Agents",
    agentsTitle: "AI Investigation Agents",
    agentsSub: "Specialized AI assistants that analyze case evidence, uncover hidden fraud links, and suggest your next best steps.",
    agentsCaseLabel: "Selected Case",
    agentsRunAllTitle: "Full Case Auto-Pilot",
    agentsRunAllSub: "Scans evidence, links accounts, assesses threat, maps police jurisdiction, and drafts your report in one go.",
    agentsRunAllBtn: "Run Full Auto-Pilot",
    agentsRunningAll: "Running Auto-Pilot…",
    agentsSpecialistsTitle: "Individual Specialist Agents",
    agentsSpecialistsSub: "Run individual focused agents to inspect specific parts of the case.",
    agentsHistoryTitle: "Investigation History & Audit Trail",
    agentsHistorySub: "Every automated agent run is recorded here with its complete findings.",
    agentsReady: "Ready to run",
    agentsRunning: "Analyzing…",
    agentsCompleted: "Completed",
    agentsNeedsAttention: "Needs review",
    agentsFailed: "Failed",
    agentsRunBtn: "Run Agent",
    agentsRunAgainBtn: "Run Again",
    agentsViewFindings: "View Findings",
    agentsHideFindings: "Hide Findings",
    agentsNoRunsYet: "No agents have run on this case yet.",
    agentsKeyFindings: "What we discovered",
    agentsNextSteps: "Suggested next steps",
    agentsStepsTaken: "Steps performed",
    registerCase: "Register New Case",
    searchLabel: "Search cases",
    searchPlaceholder: "Case no., victim or district",
    searchBtn: "Search",
    noResults: "No matching cases found",
    matchingCases: "Matching cases",
    signOut: "Sign out",
    badge: "Badge ID",
    officer: "Officer",
    investigatingOfficer: "Investigating Officer",
    home: "Home",
    mainNav: "Main navigation",
    districtPending: "District pending",
    opensInNewTab: "(opens in a new tab)",

    // ── Login ────────────────────────────────────────────────────────────
    loginTitle: "Officer Sign-In",
    loginSub: "Authorised investigating officers only.",
    loginNoticeTitle: "Important Notice",
    loginNoticeList: [
      "This system contains sensitive investigative information and is restricted to authorised officers.",
      "All access and activity is logged and monitored.",
      "Unauthorised access, disclosure or misuse is punishable under applicable law.",
      "Sign out and close the browser when you leave your workstation.",
    ],
    loginPanelTitle: "Sign in to your account",
    loginOfficerIdLabel: "Officer / Badge ID",
    loginPasswordLabel: "Password",
    loginAuthenticating: "Authenticating…",
    loginSubmit: "Secure sign-in",
    loginEmptyError: "Please enter your Officer ID and password.",
    loginFailedTitle: "Sign-in failed",
    loginDefaultError: "Authentication failed. Check your badge ID and password.",
    loginNetworkError: "Unable to reach the TraceX server. Please check your connection and try again.",
    loginForgotPassword: "Forgot password?",
    forgotPasswordTitle: "Password Reset Request",
    forgotPasswordMsg: "Please contact your System Administrator to reset your password. Provide your Officer Badge ID and police station credentials for verification.",

    // ── Dashboard ────────────────────────────────────────────────────────
    dashTitle: "Case Management Dashboard",
    loggedInAs: "Logged in as",
    badgeIdLabel: "Badge ID",
    refreshData: "Refresh Data",
    refreshingData: "Refreshing…",
    caseSummaryStats: "Case summary statistics",
    highRiskCases: "High-Risk Cases",
    highRiskCasesNote: "Cases rated High risk",
    activeCaseLoad: "Active Case Load",
    activeCaseLoadNote: "Cases not yet closed",
    awaitingCorrelation: "Awaiting Correlation",
    awaitingCorrelationNote: "Evidence uploaded, correlation pending",
    closedThisMonth: "Closed This Month",
    closedThisMonthNote: "Cases closed in the current month",
    requiresAttention: "Requires attention",

    urgentActionRequired: "URGENT ACTION REQUIRED",
    takeAction: "Take Action",
    freezeActionRecommended: "Freeze action is recommended.",

    priorityCaseRegister: "Priority Case Register",
    priorityCaseRegisterDistrict: "Priority Case Register — District:",
    showingCasesCount: "Showing {count} of {total} case(s), ranked by risk score",
    loadingRegister: "Loading case register…",
    loadingGeneral: "Loading…",
    noCasesRegisteredYet: "No cases have been registered yet. Use “Register New Case” to begin.",
    noCasesForDistrict: "No cases are recorded for the selected district.",
    filterApplied: "Filter applied:",
    clearFilter: "Clear filter",
    showTop5Only: "Show top 5 only",
    viewAllCases: "View all {count} cases",
    viewCase: "View Case",

    // Table Headers
    thSNo: "S.No.",
    thCaseNo: "Case No.",
    thComplainant: "Complainant (Victim)",
    thCategory: "Category",
    thDistrict: "District",
    thRiskLevel: "Risk Level",
    thRiskScore: "Risk Score",
    thGrounds: "Grounds for Flagging",
    thAction: "Action",
    thFileName: "File Name",
    thRows: "Rows",
    thSha256: "SHA-256 Hash",
    thStatus: "Status",
    thUploaded: "Uploaded",
    thCases: "Cases",
    thDensityLevel: "Density Level",
    thRelativeShare: "Relative Share",
    thFilter: "Filter",
    filterCasesBtn: "Filter cases",

    // Evidence Register
    evidenceRegisterTitle: "Evidence Processing Register",
    evidenceFilesQueue: "{count} file(s) in queue",
    evidenceFooterNotice: "Every uploaded file is automatically hashed (SHA-256), parsed and indexed on ingestion to preserve the chain of custody.",
    loadingEvidenceRegister: "Loading evidence register…",
    noEvidenceAwaiting: "No evidence files are awaiting processing.",
    hashPending: "Hash pending",

    // District Distribution
    districtDistTitle: "District-wise Case Distribution",
    districtDistMeta: "Jurisdictional fraud density",
    districtDistFooter: "Density levels — Low: 1–2 cases · Medium: 3–5 cases · High: 6 or more cases. District resolution uses locally bundled IFSC and postal PIN lookups (no external services).",
    loadingDistrictTelemetry: "Loading district telemetry…",
    primaryConcentration: "Primary concentration in {district} ({count} case(s)) across {total} jurisdiction(s).",
    districtDefaultTelemetry: "District data is resolved from static IFSC and postal PIN databases.",
    densityLevelLabel: "Density level:",
    allLevels: "All levels",
    levelHigh: "High",
    levelMedium: "Medium",
    levelLow: "Low",
    loadingDistrictDistribution: "Loading district distribution…",
    noDistrictForDensity: "No district data available for the selected density level.",

    // ── Correlation Page ─────────────────────────────────────────────────
    caseCorrelationTitle: "Case {caseNo} — Correlation & Network Analysis",
    caseCorrelationSub: "Multi-hop correlation of entities identified across all ingested evidence.",
    switchCaseLabel: "Switch case",
    backToDashboard: "Back to Dashboard",
    generateReports: "Generate Reports",
    unableToLoadCase: "Unable to load case data",
    failedToLoadGraph: "Failed to load graph data for this case.",

    caseDetailsTitle: "Case Details",
    cdCaseNumber: "Case Number",
    cdStatus: "Status",
    cdComplainant: "Complainant (Victim)",
    cdRiskLevel: "Risk Level",
    cdCategory: "Category",
    cdRiskScore: "Risk Score",
    cdDistrict: "District",
    cdRegisteredOn: "Registered On",
    cdRegisteredBy: "Registered By",
    cdPoliceStation: "Police Station",
    cdGrounds: "Grounds for Flagging",
    pendingValue: "Pending",

    correlationSummary: "Correlation summary",
    totalEntities: "Total Entities",
    totalConnections: "Total Connections",
    highRiskEntities: "High-Risk Entities",
    crossCaseLinks: "Cross-Case Links",

    entityRegisterTitle: "Entity Register",
    showingEntitiesCount: "{shown} of {total} entities",
    entityTypeFilterLabel: "Entity type:",
    allTypes: "All types",
    thEntityType: "Entity Type",
    thIdentifier: "Identifier",
    thConnections: "Connections",
    thSource: "Source",
    thRemarks: "Remarks",
    sourceThisCase: "This case",
    sourceOtherCase: "Other case",
    loadingEntityRegister: "Loading entity register…",
    noEntitiesMatch: "No entities match the selected filters.",

    connectionRegisterTitle: "Connection Register",
    connectionRegisterMeta: "{count} linked pair(s), highest confidence first",
    thEntityA: "Entity A",
    thEntityB: "Entity B",
    thBasisOfLink: "Basis of Link",
    thConfidence: "Confidence",
    thCrossCase: "Cross-Case",
    thEvidenceRef: "Evidence Ref.",
    loadingConnectionRegister: "Loading connection register…",
    noConnectionsForCase: "No connections have been established for this case.",
    yesLabel: "Yes",
    noLabel: "No",

    narrativeTitle: "System-Generated Case Narrative",
    regenerateNarrative: "Regenerate Narrative",
    regeneratingNarrative: "Regenerating…",
    narrativeFooter: "Advisory only: this narrative is machine-generated from ingested evidence and must be verified by the Investigating Officer before any action is taken.",
    narrativeUnavailable: "Narrative unavailable",
    narrativeFailedMsg: "The narrative could not be regenerated. Please try again.",
    keyDirectivesTitle: "Key Directives",
    generatedVia: "Generated via",
    noNarrativeYet: "No correlation narrative has been generated yet. Upload multi-source evidence and run correlation to generate a brief.",

    figureNetworkDiagram: "Figure 1: Network Diagram",
    hideDiagram: "Hide diagram",
    showDiagram: "Show diagram",
    loadingDiagram: "Loading diagram…",
    noDiagramEntities: "No correlated entities are available to plot for this case.",

    // ── Reports Page ─────────────────────────────────────────────────────
    reportsPageTitle: "Case {caseNo} — Certified Forensic Reports",
    reportsPageSub: "Certified law-enforcement exports formatted for courtroom admissibility under Section 65B of the Indian Evidence Act.",
    pwdProtectedExportsTitle: "Password-protected exports",
    pwdProtectedExportsBody: "Each report is encrypted at file level. To open the downloaded PDF, enter your officer account password or Badge ID.",
    downloadFailedTitle: "Download failed",
    briefGenFailed: "The Investigative Brief could not be generated. Please try again.",
    takedownGenFailed: "The Takedown Notice could not be generated. Please try again.",
    availableReportsTitle: "Available Reports",
    thReport: "Report",
    thLegalBasis: "Legal Basis",
    thDescription: "Description",
    downloadProtectedPdf: "Download Protected PDF",
    generatingEncryptedPdf: "Generating Encrypted PDF…",
    encryptedAndVerified: "Encrypted & verified",
    contentsPrefix: "Contents:",

    briefDossierName: "Investigative Brief Dossier",
    briefDossierBasis: "Section 65B, Indian Evidence Act (certified)",
    briefDossierDesc: "Law-enforcement dossier containing the executive narrative, category entity landscape, multi-hop correlation matrix, chronological case timeline and Section 91 CrPC freeze directives.",
    briefContents: [
      "30-second executive summary and risk progress score",
      "Category breakdown matching the network graph colour language",
      "Multi-hop correlation matrix with confidence scoring",
      "Section 91 CrPC bank debit-freeze and telecom seizure directives",
    ],

    takedownNoticeName: "Statutory Takedown Notice",
    takedownNoticeBasis: "Section 69A, Information Technology Act",
    takedownNoticeDesc: "Statutory emergency advisory served upon domain registrars, hosting providers, ISPs and telecom intermediaries with mandatory 24-hour compliance terms.",
    takedownContents: [
      "Emergency 24-hour public resolution disabling and DNS sinkhole mandate",
      "Cyber attack infrastructure table with priority CRITICAL / HIGH markings",
      "180-day server access log preservation order under Section 67C IT Act",
      "Threat intelligence and forensic justification for blocking",
    ],

    // ── Register New Case Modal ──────────────────────────────────────────
    regModalTitle: "Register New Case",
    regModalSub: "Register the incident and ingest multi-source evidence artifacts",
    regModalClose: "Close",
    regModalUnableToProceed: "Unable to proceed",
    regModalCaseCreated: "Case registered",
    regModalReadyForIngestion: "Ready for evidence ingestion.",
    regModalVictimNameLabel: "Victim's Full Name",
    regModalVictimPlaceholder: "e.g. Rajesh Kumar",
    regModalRegDateLabel: "Date of Case Registration",
    regModalScamTypeLegend: "Scam Type Classification *",
    regModalScamOptions: {
      digital_scam: { title: "Digital Scam", desc: "UPI fraud, fraudulent loan apps, part-time job and investment tasks" },
      phishing_vishing: { title: "Phishing / Vishing", desc: "SIM swap, fake KYC calls, caller ID spoofing and bank impersonation" },
      malicious_apk: { title: "Malicious APK", desc: "Trojanized APKs, SMS forwarders, accessibility service abuse and C2 beacons" },
    },
    regModalIngestLegend: "Ingest Evidence Files",
    regModalIngestHint: "Accepted formats: CSV, XLSX, IPDR, CDR, forensic logs. Enter the victim's name first; the case is created on the first upload.",
    regModalUploadZones: {
      telecom: { label: "Telecom Evidence", sub: "CDR, IPDR, cell tower records" },
      bank_upi: { label: "Bank & UPI Evidence", sub: "Statements, UPI handles" },
      other: { label: "Other Artifacts", sub: "APK report, intelligence, URLs" },
    },
    regModalChooseFile: "Choose file",
    regModalIngesting: "Ingesting…",
    regModalIngestedArtifactsCount: "Ingested Artifacts ({count})",
    regModalPipelineProgress: "Processing forensic correlation pipeline — {percent}%",
    regModalStep1: "1. Extracting entities",
    regModalStep2: "2. Building connections",
    regModalStep3: "3. Rendering graph",
    regModalCancel: "Cancel",
    regModalCorrelating: "Correlating entities…",
    regModalSubmit: "Find connections & view graph",
    regModalNameRequired: "Please enter the victim's name before uploading evidence.",
    regModalInitFailed: "Failed to initialize case.",
    regModalUploadFailed: "Failed to upload {filename}",
    regModalUploadFirst: "Please create a case and upload evidence first.",
    regModalCorrelateFailed: "Correlation failed. Please check evidence files.",

    // ── Report Password Modal ────────────────────────────────────────────
    pwdModalTitle: "Protected Document Export",
    pwdModalSub: "File-level password encryption",
    pwdModalClose: "Close",
    pwdModalReportRow: "Report",
    pwdModalCaseRefRow: "Case Reference",
    pwdModalNoticeBody: "In compliance with statutory evidentiary chain-of-custody protocols, the downloaded PDF will be password-protected at the file level. Enter your current officer login password to authorise encryption.",
    pwdModalErrorTitle: "Unable to generate the document",
    pwdModalPasswordLabel: "Officer Account Password",
    pwdModalShowPassword: "Show password",
    pwdModalRecipientHint: "The recipient will be prompted for this exact password when opening the file.",
    pwdModalCancel: "Cancel",
    pwdModalEncrypting: "Encrypting & downloading…",
    pwdModalSubmit: "Download Encrypted PDF",
    pwdModalRequiredError: "Please enter your officer account password.",

    // ── Footer ───────────────────────────────────────────────────────────
    footerRelatedPortals: "Related Portals",
    footerPortals: [
      { label: "National Cyber Crime Reporting Portal", href: "https://cybercrime.gov.in" },
      { label: "Indian Cyber Crime Coordination Centre (I4C)", href: "https://i4c.mha.gov.in" },
      { label: "CERT-In — Indian Computer Emergency Response Team", href: "https://www.cert-in.org.in" },
    ],
    footerStatutoryReferences: "Statutory References",
    footerStatutes: [
      "Information Technology Act, 2000 — Sections 66C, 66D and 69A",
      "Indian Evidence Act — Section 65B certification",
      "Section 91 CrPC — production of documents / debit-freeze directions",
    ],
    footerHelplines: "Helplines",
    footerHelplineNumber: "1930",
    footerHelplineDesc: "National Cyber Crime Helpline (toll free)",
    footerCitizenComplaints: "Citizen complaints: cybercrime.gov.in",
    footerAdvisoryNoticeTitle: "Advisory notice:",
    footerAdvisoryNoticeBody: "TraceX is an investigative decision-support system for authorised officers. Risk ratings, correlation scores and AI-generated narratives are advisory and must be verified by the Investigating Officer before any legal action is initiated. Access is restricted, logged and monitored; unauthorised access or misuse is punishable under applicable law.",
    footerCopyright: "© {year} TraceX. All rights reserved.",
    footerBackToTop: "Back to top",

    // ── AI Chatbot ───────────────────────────────────────────────────────
    chatLauncherTitle: "Open TraceX Cyber AI Assistant",
    chatLauncherBrand: "TraceX Cyber AI",
    chatLauncherGlobal: "Global Intelligence",
    chatLauncherLive: "LIVE",
    chatWindowTitle: "TraceX AI Assistant",
    chatOnline: "ONLINE",
    chatActiveContext: "Active Context: {caseLabel}",
    chatGlobalContext: "Global Threat Intelligence Network",
    chatClearTitle: "Clear Conversation Thread",
    chatClearBtn: "Clear",
    chatRestoreWidth: "Restore Standard Width",
    chatExpandWidth: "Expand Window Width",
    chatCloseTitle: "Close Window (Escape)",
    chatSuggestedPrefix: "Suggested:",
    chatOfficerSender: "Officer",
    chatModelSender: "TraceX Intelligence Model",
    chatCopyTitle: "Copy intelligence message",
    chatNextActions: "Next Recommended Actions:",
    chatAnalyzingIndicator: "Analyzing intelligence databases, Mule graphs & telecom records...",
    chatPlaceholderCase: "Ask TraceX AI about {caseLabel}...",
    chatPlaceholderGlobal: "Ask about high-risk entities, scam clusters, or legal notices...",
    chatSendTitle: "Send Question",
    chatSecurityFooter: "Intelligence engine v2.4 • End-to-end encrypted",
    chatEscHint: "Press Esc to close window",
    chatWelcomeMessage: "Hello Officer. I am your TraceX Cyber Intelligence Assistant. Ask me questions regarding the active case investigation, mule accounts, APK threat signatures, or cross-case fraud analytics across the state network.",
    chatClearedMessage: "Chat history cleared. How can I assist your investigation today?",
    chatQuickPromptsCase: [
      "⚡ Summarize this case",
      "🎯 Identify high-risk entities",
      "🏦 Detect suspect mule accounts",
      "🔗 Check cross-case connections",
      "📜 Recommended legal freeze action",
    ],
    chatQuickPromptsGlobal: [
      "📊 How many high-risk cases are open?",
      "🚨 List active investigations",
      "📈 What are the top scam trends?",
      "🛡️ State-wide Mule account summary",
    ],

    // ── Network Graph Subtitle & Hop Controls ────────────────────────────
    graphTitle: "Case Correlation Graph",
    graphSub: "Explore connections between entities. Click a category cluster to view details or hold Ctrl + scroll to zoom.",
    graphHopOverview: "Overview",
    graphHop1: "1 Hop",
    graphHop2: "2 Hops",
    graphHop3: "3 Hops",

    // ── Domain Taxonomy Labels ───────────────────────────────────────────
    scams: {
      digital_scam: "Digital Scam",
      phishing_vishing: "Phishing / Vishing",
      malicious_apk: "Malicious APK",
    },
    entities: {
      upi_handle: "UPI Handle",
      account: "Bank Account",
      phone: "Phone",
      imei: "IMEI / Device",
      imsi: "SIM / IMSI",
      ip_address: "IP Address",
      apk_hash: "Malicious APK",
      email: "Email",
      url: "URL / Website",
    },
    evidenceCategories: {
      telecom: "Telecom",
      bank_upi: "Bank / UPI",
      other: "Other Artifacts",
    },
    statuses: {
      open: "Open",
      correlating: "Correlating",
      under_review: "Under Review",
      closed: "Closed",
    },
    evidenceStatuses: {
      queued: "Queued",
      pending: "Pending",
      processing: "Processing",
      completed: "Indexed",
      indexed: "Indexed",
      error: "Error",
      failed: "Error",
    },
    risks: {
      critical: "Critical",
      high: "High",
      medium: "Medium",
      low: "Low",
      unrated: "Unrated",
    },
  },

  hi: {
    // ── Shell, Navigation & Utility ──────────────────────────────────────
    skip: "मुख्य सामग्री पर जाएँ",
    textSize: "अक्षर आकार",
    textSizeDecrease: "अक्षर का आकार छोटा करें",
    textSizeDefault: "सामान्य अक्षर आकार",
    textSizeIncrease: "अक्षर का आकार बड़ा करें",
    contrast: "उच्च कंट्रास्ट",
    displayMode: "प्रदर्शन मोड",
    standard: "मानक",
    analysis: "विश्लेषण",
    language: "भाषा",
    dashboard: "डैशबोर्ड",
    correlation: "सहसंबंध एवं ग्राफ़",
    reports: "रिपोर्ट",
    agents: "एआई एजेंट",
    agentsTitle: "एआई जाँच एजेंट",
    agentsSub: "विशेषज्ञ एआई सहायक जो साक्ष्यों का विश्लेषण करते हैं, छिपे हुए संबंधों का पता लगाते हैं और अगली उचित कार्रवाई सुझाते हैं।",
    agentsCaseLabel: "चयनित प्रकरण",
    agentsRunAllTitle: "सम्पूर्ण केस ऑटो-पायलट",
    agentsRunAllSub: "एक ही क्लिक में साक्ष्यों की जांच, बैंक लिंक, जोखिम स्कोर, क्षेत्राधिकार और रिपोर्ट तैयार करें।",
    agentsRunAllBtn: "ऑटो-पायलट शुरू करें",
    agentsRunningAll: "ऑटो-पायलट प्रगति पर…",
    agentsSpecialistsTitle: "व्यक्तिगत विशेषज्ञ एजेंट",
    agentsSpecialistsSub: "प्रकरण के किसी विशिष्ट भाग की विस्तृत जाँच हेतु व्यक्तिगत एजेंट चलाएं।",
    agentsHistoryTitle: "जाँच इतिहास एवं ऑडिट लॉग",
    agentsHistorySub: "प्रत्येक एआई एजेंट द्वारा की गई जाँच और परिणाम यहाँ सुरक्षित दर्ज रहते हैं।",
    agentsReady: "तैयार",
    agentsRunning: "विश्लेषण जारी…",
    agentsCompleted: "पूर्ण",
    agentsNeedsAttention: "समीक्षा आवश्यक",
    agentsFailed: "विफल",
    agentsRunBtn: "एजेंट चलाएं",
    agentsRunAgainBtn: "पुनः चलाएं",
    agentsViewFindings: "परिणाम देखें",
    agentsHideFindings: "परिणाम छिपाएं",
    agentsNoRunsYet: "इस प्रकरण पर अभी कोई एआई एजेंट नहीं चलाया गया है।",
    agentsKeyFindings: "मुख्य निष्कर्ष",
    agentsNextSteps: "अनुशंसित अग्रिम कार्रवाई",
    agentsStepsTaken: "किए गए चरण",
    registerCase: "नया प्रकरण पंजीकृत करें",
    searchLabel: "प्रकरण खोजें",
    searchPlaceholder: "प्रकरण क्रमांक, पीड़ित या ज़िला",
    searchBtn: "खोजें",
    noResults: "कोई मिलान प्रकरण नहीं मिला",
    matchingCases: "मिलान प्रकरण",
    signOut: "साइन आउट",
    badge: "बैज आईडी",
    officer: "अधिकारी",
    investigatingOfficer: "जाँच अधिकारी",
    home: "मुख्य पृष्ठ",
    mainNav: "मुख्य नेविगेशन",
    districtPending: "ज़िला लंबित",
    opensInNewTab: "(नई विंडो में खुलता है)",

    // ── Login ────────────────────────────────────────────────────────────
    loginTitle: "अधिकारी साइन-इन",
    loginSub: "केवल अधिकृत जाँच अधिकारियों के लिए।",
    loginNoticeTitle: "महत्वपूर्ण सूचना",
    loginNoticeList: [
      "इस प्रणाली में संवेदनशील अन्वेषण डेटा है और यह केवल अधिकृत अधिकारियों हेतु प्रतिबंधित है।",
      "सभी पहुँच और गतिविधियाँ लॉग व निरंतर निगरानी में रखी जाती हैं।",
      "अनाधिकृत पहुँच, प्रकटीकरण या दुरुपयोग लागू कानूनों के अंतर्गत दंडनीय है।",
      "कार्यस्थल छोड़ने से पूर्व साइन आउट करें और ब्राउज़र बंद करें।",
    ],
    loginPanelTitle: "अपने खाते में साइन-इन करें",
    loginOfficerIdLabel: "अधिकारी / बैज आईडी",
    loginPasswordLabel: "पासवर्ड",
    loginAuthenticating: "सत्यापन हो रहा है…",
    loginSubmit: "सुरक्षित साइन-इन",
    loginEmptyError: "कृपया अपनी अधिकारी आईडी और पासवर्ड दर्ज करें।",
    loginFailedTitle: "साइन-इन विफल",
    loginDefaultError: "प्रमाणीकरण विफल। अपनी बैज आईडी और पासवर्ड की जांच करें।",
    loginNetworkError: "ट्रेसएक्स सर्वर से संपर्क करने में असमर्थ। कृपया अपना इंटरनेट कनेक्शन जांचें और पुनः प्रयास करें।",
    loginForgotPassword: "पासवर्ड भूल गए?",
    forgotPasswordTitle: "पासवर्ड रीसेट अनुरोध",
    forgotPasswordMsg: "अपना पासवर्ड रीसेट करने के लिए कृपया अपने सिस्टम व्यवस्थापक से संपर्क करें। प्रमाणीकरण हेतु अपनी अधिकारी बैज आईडी और थाना विवरण प्रदान करें।",

    // ── Dashboard ────────────────────────────────────────────────────────
    dashTitle: "प्रकरण प्रबंधन डैशबोर्ड",
    loggedInAs: "लॉग-इन अधिकारी",
    badgeIdLabel: "बैज आईडी",
    refreshData: "डेटा रीफ्रेश करें",
    refreshingData: "रीफ्रेश हो रहा है…",
    caseSummaryStats: "प्रकरण सारांश सांख्यिकी",
    highRiskCases: "उच्च-जोखिम प्रकरण",
    highRiskCasesNote: "उच्च जोखिम श्रेणी में वर्गीकृत प्रकरण",
    activeCaseLoad: "सक्रिय प्रकरण भार",
    activeCaseLoadNote: "वर्तमान में अनिस्तारित प्रकरण",
    awaitingCorrelation: "सहसंबंध प्रतीक्षारत",
    awaitingCorrelationNote: "साक्ष्य अपलोड हो चुके हैं, सहसंबंध विश्लेषण शेष",
    closedThisMonth: "इस माह निस्तारित",
    closedThisMonthNote: "वर्तमान माह में निस्तारित किए गए प्रकरण",
    requiresAttention: "कार्रवाई आवश्यक",

    urgentActionRequired: "अति आवश्यक कार्रवाई अपेक्षित",
    takeAction: "कार्रवाई करें",
    freezeActionRecommended: "खाता फ़्रीज़ कार्रवाई की अनुशंसा की गई है।",

    priorityCaseRegister: "प्राथमिकता प्रकरण रजिस्टर",
    priorityCaseRegisterDistrict: "प्राथमिकता प्रकरण रजिस्टर — ज़िला:",
    showingCasesCount: "जोखिम स्कोर के आधार पर {total} में से {count} प्रकरण प्रदर्शित",
    loadingRegister: "प्रकरण रजिस्टर लोड हो रहा है…",
    loadingGeneral: "लोड हो रहा है…",
    noCasesRegisteredYet: "अभी तक कोई प्रकरण पंजीकृत नहीं हुआ है। शुरुआत करने के लिए “नया प्रकरण पंजीकृत करें” का उपयोग करें।",
    noCasesForDistrict: "चयनित ज़िले के लिए कोई प्रकरण दर्ज नहीं है।",
    filterApplied: "लागू फ़िल्टर:",
    clearFilter: "फ़िल्टर हटाएं",
    showTop5Only: "केवल शीर्ष 5 देखें",
    viewAllCases: "सभी {count} प्रकरण देखें",
    viewCase: "प्रकरण देखें",

    // Table Headers
    thSNo: "क्र.सं.",
    thCaseNo: "प्रकरण सं.",
    thComplainant: "शिकायतकर्ता (पीड़ित)",
    thCategory: "श्रेणी",
    thDistrict: "ज़िला",
    thRiskLevel: "जोखिम स्तर",
    thRiskScore: "जोखिम स्कोर",
    thGrounds: "चिह्नित करने का आधार",
    thAction: "कार्रवाई",
    thFileName: "फ़ाइल का नाम",
    thRows: "पंक्तियाँ",
    thSha256: "SHA-256 हैश",
    thStatus: "स्थिति",
    thUploaded: "अपलोड तिथि",
    thCases: "प्रकरण संख्या",
    thDensityLevel: "घनत्व स्तर",
    thRelativeShare: "सापेक्ष अनुपात",
    thFilter: "फ़िल्टर",
    filterCasesBtn: "प्रकरण फ़िल्टर करें",

    // Evidence Register
    evidenceRegisterTitle: "साक्ष्य प्रसंस्करण रजिस्टर",
    evidenceFilesQueue: "कतार में {count} फ़ाइल(ें)",
    evidenceFooterNotice: "कस्टडी की श्रृंखला बनाए रखने के लिए अपलोड की गई प्रत्येक फ़ाइल को अंतर्ग्रहण पर स्वचालित रूप से हैश (SHA-256), पार्स और इंडेक्स किया जाता है।",
    loadingEvidenceRegister: "साक्ष्य रजिस्टर लोड हो रहा है…",
    noEvidenceAwaiting: "प्रसंस्करण के लिए कोई साक्ष्य फ़ाइल लंबित नहीं है।",
    hashPending: "हैश लंबित",

    // District Distribution
    districtDistTitle: "ज़िला-वार प्रकरण वितरण",
    districtDistMeta: "क्षेत्राधिकार धोखाधड़ी घनत्व",
    districtDistFooter: "घनत्व स्तर — निम्न: 1–2 प्रकरण · मध्यम: 3–5 प्रकरण · उच्च: 6 या अधिक प्रकरण। ज़िला निर्धारण स्थानीय रूप से बंडल किए गए आईएफएससी और पिन कोड से किया जाता है।",
    loadingDistrictTelemetry: "ज़िला टेलीमेट्री लोड हो रही है…",
    primaryConcentration: "{total} क्षेत्राधिकारों में से प्रमुख सांद्रता <strong>{district}</strong> ({count} प्रकरण) में है।",
    districtDefaultTelemetry: "ज़िला डेटा स्थानीय आईएफएससी और पिन कोड डेटाबेस से निर्धारित होता है।",
    densityLevelLabel: "घनत्व स्तर:",
    allLevels: "सभी स्तर",
    levelHigh: "उच्च",
    levelMedium: "मध्यम",
    levelLow: "निम्न",
    loadingDistrictDistribution: "ज़िला वितरण डेटा लोड हो रहा है…",
    noDistrictForDensity: "चयनित घनत्व स्तर के लिए कोई ज़िला डेटा उपलब्ध नहीं है।",

    // ── Correlation Page ─────────────────────────────────────────────────
    caseCorrelationTitle: "प्रकरण {caseNo} — सहसंबंध एवं नेटवर्क विश्लेषण",
    caseCorrelationSub: "अंतर्ग्रहीत सभी साक्ष्यों के आधार पर संस्थाओं का बहु-चरणीय (Multi-hop) सहसंबंध।",
    switchCaseLabel: "प्रकरण बदलें",
    backToDashboard: "डैशबोर्ड पर वापस जाएं",
    generateReports: "रिपोर्ट जनरेट करें",
    unableToLoadCase: "प्रकरण डेटा लोड करने में असमर्थ",
    failedToLoadGraph: "इस प्रकरण के लिए ग्राफ़ डेटा लोड करने में विफल।",

    caseDetailsTitle: "प्रकरण विवरण",
    cdCaseNumber: "प्रकरण क्रमांक",
    cdStatus: "स्थिति",
    cdComplainant: "शिकायतकर्ता (पीड़ित)",
    cdRiskLevel: "जोखिम स्तर",
    cdCategory: "धोखाधड़ी श्रेणी",
    cdRiskScore: "जोखिम स्कोर",
    cdDistrict: "ज़िला",
    cdRegisteredOn: "पंजीकरण तिथि",
    cdRegisteredBy: "पंजीकरणकर्ता",
    cdPoliceStation: "थाना",
    cdGrounds: "चिह्नित करने का आधार",
    pendingValue: "लंबित",

    correlationSummary: "सहसंबंध सारांश",
    totalEntities: "कुल संस्थाएँ (Entities)",
    totalConnections: "कुल संबंध (Connections)",
    highRiskEntities: "उच्च-जोखिम संस्थाएँ",
    crossCaseLinks: "क्रॉस-केस लिंक्स",

    entityRegisterTitle: "संस्था रजिस्टर (Entity Register)",
    showingEntitiesCount: "कुल {total} में से {shown} संस्थाएँ",
    entityTypeFilterLabel: "संस्था प्रकार:",
    allTypes: "सभी प्रकार",
    thEntityType: "संस्था प्रकार",
    thIdentifier: "पहचानकर्ता / विवरण",
    thConnections: "संबंध संख्या",
    thSource: "स्रोत",
    thRemarks: "टिप्पणी",
    sourceThisCase: "यह प्रकरण",
    sourceOtherCase: "अन्य प्रकरण",
    loadingEntityRegister: "संस्था रजिस्टर लोड हो रहा है…",
    noEntitiesMatch: "चयनित फ़िल्टर से मेल खाती कोई संस्था नहीं है।",

    connectionRegisterTitle: "संबंध रजिस्टर (Connection Register)",
    connectionRegisterMeta: "{count} संबंधित युग्म, उच्चतम विश्वसनीयता पहले",
    thEntityA: "संस्था अ",
    thEntityB: "संस्था ब",
    thBasisOfLink: "संबंध का आधार",
    thConfidence: "विश्वसनीयता",
    thCrossCase: "क्रॉस-केस",
    thEvidenceRef: "साक्ष्य संदर्भ",
    loadingConnectionRegister: "संबंध रजिस्टर लोड हो रहा है…",
    noConnectionsForCase: "इस प्रकरण के लिए अभी कोई संबंध स्थापित नहीं हुआ है।",
    yesLabel: "हाँ",
    noLabel: "नहीं",

    narrativeTitle: "प्रणाली द्वारा जनरेट किया गया प्रकरण विवरण",
    regenerateNarrative: "विवरण पुन: जनरेट करें",
    regeneratingNarrative: "पुन: जनरेट हो रहा है…",
    narrativeFooter: "केवल परामर्श हेतु: यह विवरण अंतर्ग्रहीत साक्ष्यों से कंप्यूटर द्वारा जनरेट किया गया है और कोई भी कार्रवाई करने से पहले जाँच अधिकारी द्वारा इसका सत्यापन अनिवार्य है।",
    narrativeUnavailable: "विवरण अनुपलब्ध",
    narrativeFailedMsg: "विवरण पुन: जनरेट नहीं किया जा सका। कृपया पुनः प्रयास करें।",
    keyDirectivesTitle: "प्रमुख कानूनी निर्देश",
    generatedVia: "जनरेट किया गया माध्यम:",
    noNarrativeYet: "अभी तक कोई सहसंबंध विवरण जनरेट नहीं हुआ है। संक्षिप्त विवरण तैयार करने के लिए बहु-स्रोत साक्ष्य अपलोड करें और सहसंबंध चलाएं।",

    figureNetworkDiagram: "चित्र 1: नेटवर्क आरेख",
    hideDiagram: "आरेख छिपाएँ",
    showDiagram: "आरेख दिखाएँ",
    loadingDiagram: "आरेख लोड हो रहा है…",
    noDiagramEntities: "इस प्रकरण के लिए आरेखित करने हेतु कोई सहसंबंधित संस्था उपलब्ध नहीं है।",

    // ── Reports Page ─────────────────────────────────────────────────────
    reportsPageTitle: "प्रकरण {caseNo} — प्रमाणित फॉरेंसिक रिपोर्ट",
    reportsPageSub: "भारतीय साक्ष्य अधिनियम की धारा 65B के अंतर्गत न्यायालय में ग्राह्यता हेतु तैयार प्रमाणित कानूनी निर्यात।",
    pwdProtectedExportsTitle: "पासवर्ड-संरक्षित निर्यात",
    pwdProtectedExportsBody: "प्रत्येक रिपोर्ट फ़ाइल स्तर पर एन्क्रिप्टेड है। डाउनलोड की गई पीडीएफ खोलने के लिए अपना अधिकारी खाता पासवर्ड या बैज आईडी दर्ज करें।",
    downloadFailedTitle: "डाउनलोड विफल",
    briefGenFailed: "जाँच संक्षेपिका (Investigative Brief) जनरेट नहीं की जा सकी। कृपया पुनः प्रयास करें।",
    takedownGenFailed: "टेकडाउन नोटिस जनरेट नहीं किया जा सका। कृपया पुनः प्रयास करें।",
    availableReportsTitle: "उपलब्ध रिपोर्ट",
    thReport: "रिपोर्ट का नाम",
    thLegalBasis: "कानूनी आधार",
    thDescription: "विवरण",
    downloadProtectedPdf: "सुरक्षित पीडीएफ डाउनलोड करें",
    generatingEncryptedPdf: "एन्क्रिप्टेड पीडीएफ तैयार हो रही है…",
    encryptedAndVerified: "एन्क्रिप्टेड एवं सत्यापित",
    contentsPrefix: "सामग्री:",

    briefDossierName: "जाँच संक्षेपिका डॉसियर (Investigative Brief)",
    briefDossierBasis: "भारतीय साक्ष्य अधिनियम, धारा 65B (प्रमाणित)",
    briefDossierDesc: "कार्यकारी सारांश, संस्था परिदृश्य, बहु-चरणीय सहसंबंध मैट्रिक्स, कालानुक्रमिक समयरेखा और धारा 91 सीआरपीसी फ़्रीज़ निर्देशों से युक्त डॉसियर।",
    briefContents: [
      "30-सेकंड कार्यकारी सारांश एवं प्रगतिशील जोखिम स्कोर",
      "नेटवर्क ग्राफ़ के रंग अनुरूप श्रेणीवार विवरण",
      "विश्वसनीयता स्कोरिंग के साथ मल्टी-हॉप सहसंबंध मैट्रिक्स",
      "धारा 91 सीआरपीसी बैंक डेबिट-फ़्रीज़ एवं दूरसंचार जब्ती निर्देश",
    ],

    takedownNoticeName: "वैधानिक टेकडाउन नोटिस (Takedown Notice)",
    takedownNoticeBasis: "सूचना प्रौद्योगिकी अधिनियम, धारा 69A",
    takedownNoticeDesc: "डोमेन रजिस्ट्रार, होस्टिंग प्रदाताओं, आईएसपी और दूरसंचार मध्यवर्तियों को 24 घंटे की अनिवार्य अनुपालन शर्तों के साथ जारी आपातकालीन नोटिस।",
    takedownContents: [
      "आपातकालीन 24 घंटे में सार्वजनिक रिज़ॉल्यूशन निरस्तीकरण व डीएनएस सिंकहोल अधिदेश",
      "क्रिटिकल / हाई चिह्नों के साथ साइबर हमला अवसंरचना तालिका",
      "आईटी एक्ट की धारा 67C के तहत 180 दिन का सर्वर एक्सेस लॉग संरक्षण आदेश",
      "अवरोधन के लिए थ्रेट इंटेलिजेंस और फॉरेंसिक औचित्य",
    ],

    // ── Register New Case Modal ──────────────────────────────────────────
    regModalTitle: "नया प्रकरण पंजीकृत करें",
    regModalSub: "घटना का विवरण दर्ज करें और बहु-स्रोत साक्ष्य फ़ाइलें प्रविष्ट करें",
    regModalClose: "बंद करें",
    regModalUnableToProceed: "आगे बढ़ने में असमर्थ",
    regModalCaseCreated: "प्रकरण पंजीकृत",
    regModalReadyForIngestion: "साक्ष्य अंतर्ग्रहण के लिए तैयार।",
    regModalVictimNameLabel: "पीड़ित का पूरा नाम",
    regModalVictimPlaceholder: "उदा. राजेश कुमार",
    regModalRegDateLabel: "प्रकरण पंजीकरण की तिथि",
    regModalScamTypeLegend: "धोखाधड़ी प्रकार वर्गीकरण *",
    regModalScamOptions: {
      digital_scam: { title: "डिजिटल धोखाधड़ी (Digital Scam)", desc: "यूपीआई फ्रॉड, फ़र्ज़ी लोन ऐप्स, पार्ट-टाइम जॉब व निवेश कार्य" },
      phishing_vishing: { title: "फ़िशिंग / विशिंग (Phishing / Vishing)", desc: "सिम स्वैप, फ़र्ज़ी केवाईसी कॉल, कॉलर आईडी स्पूफ़िंग व बैंक प्रतिरूपण" },
      malicious_apk: { title: "दुर्भावनापूर्ण एपीके (Malicious APK)", desc: "ट्रोजन युक्त एपीके, एसएमएस फ़ॉरवर्डर्स, एक्सेसिबिलिटी सेवा दुरुपयोग व C2 बीकन्स" },
    },
    regModalIngestLegend: "साक्ष्य फ़ाइलें प्रविष्ट करें",
    regModalIngestHint: "स्वीकृत प्रारूप: CSV, XLSX, IPDR, CDR, फॉरेंसिक लॉग। पहले पीड़ित का नाम दर्ज करें; पहली अपलोड पर प्रकरण बन जाएगा।",
    regModalUploadZones: {
      telecom: { label: "दूरसंचार साक्ष्य (Telecom)", sub: "CDR, IPDR, मोबाइल टॉवर रिकॉर्ड" },
      bank_upi: { label: "बैंक एवं यूपीआई साक्ष्य", sub: "खाता विवरण (Statements), यूपीआई हैंडल्स" },
      other: { label: "अन्य साक्ष्य एवं आर्टिफ़ैक्ट्स", sub: "APK रिपोर्ट, इंटेलिजेंस, यूआरएल (URLs)" },
    },
    regModalChooseFile: "फ़ाइल चुनें",
    regModalIngesting: "प्रविष्ट हो रही है…",
    regModalIngestedArtifactsCount: "प्रविष्ट साक्ष्य ({count})",
    regModalPipelineProgress: "फॉरेंसिक सहसंबंध पाइपलाइन प्रक्रियाधीन — {percent}%",
    regModalStep1: "1. संस्थाओं का निष्कर्षण",
    regModalStep2: "2. संबंधों का निर्माण",
    regModalStep3: "3. ग्राफ़ का प्रस्तुतीकरण",
    regModalCancel: "रद्द करें",
    regModalCorrelating: "संस्थाओं का सहसंबंध निकाला जा रहा है…",
    regModalSubmit: "संबंध खोजें एवं ग्राफ़ देखें",
    regModalNameRequired: "साक्ष्य अपलोड करने से पहले कृपया पीड़ित का नाम दर्ज करें।",
    regModalInitFailed: "प्रकरण प्रारंभ करने में विफल।",
    regModalUploadFailed: "{filename} अपलोड करने में विफल",
    regModalUploadFirst: "कृपया पहले एक प्रकरण बनाएं और साक्ष्य अपलोड करें।",
    regModalCorrelateFailed: "सहसंबंध विश्लेषण विफल। कृपया साक्ष्य फ़ाइलों की जांच करें।",

    // ── Report Password Modal ────────────────────────────────────────────
    pwdModalTitle: "सुरक्षित दस्तावेज़ निर्यात",
    pwdModalSub: "फ़ाइल-स्तरीय पासवर्ड एन्क्रिप्शन",
    pwdModalClose: "बंद करें",
    pwdModalReportRow: "रिपोर्ट",
    pwdModalCaseRefRow: "प्रकरण संदर्भ",
    pwdModalNoticeBody: "वैधानिक साक्ष्य श्रृंखला प्रोटोकॉल के अनुपालन में, डाउनलोड की गई पीडीएफ फ़ाइल स्तर पर पासवर्ड से सुरक्षित होगी। एन्क्रिप्शन अधिकृत करने के लिए अपना वर्तमान अधिकारी लॉगिन पासवर्ड दर्ज करें।",
    pwdModalErrorTitle: "दस्तावेज़ जनरेट करने में असमर्थ",
    pwdModalPasswordLabel: "अधिकारी खाता पासवर्ड",
    pwdModalShowPassword: "पासवर्ड दिखाएं",
    pwdModalRecipientHint: "फ़ाइल खोलते समय प्राप्तकर्ता से यही पासवर्ड माँगा जाएगा।",
    pwdModalCancel: "रद्द करें",
    pwdModalEncrypting: "एन्क्रिप्ट व डाउनलोड हो रहा है…",
    pwdModalSubmit: "सुरक्षित पीडीएफ डाउनलोड करें",
    pwdModalRequiredError: "कृपया अपना अधिकारी खाता पासवर्ड दर्ज करें।",

    // ── Footer ───────────────────────────────────────────────────────────
    footerRelatedPortals: "संबंधित पोर्टल",
    footerPortals: [
      { label: "राष्ट्रीय साइबर अपराध रिपोर्टिंग पोर्टल (NCRP)", href: "https://cybercrime.gov.in" },
      { label: "भारतीय साइबर अपराध समन्वय केंद्र (I4C)", href: "https://i4c.mha.gov.in" },
      { label: "सर्ट-इन (CERT-In) — भारतीय कंप्यूटर आपातकालीन प्रतिक्रिया दल", href: "https://www.cert-in.org.in" },
    ],
    footerStatutoryReferences: "वैधानिक संदर्भ",
    footerStatutes: [
      "सूचना प्रौद्योगिकी अधिनियम, 2000 — धारा 66C, 66D एवं 69A",
      "भारतीय साक्ष्य अधिनियम — धारा 65B प्रमाणन",
      "धारा 91 दंड प्रक्रिया संहिता (CrPC) — दस्तावेज़ प्रस्तुतिकरण / डेबिट-फ़्रीज़ निर्देश",
    ],
    footerHelplines: "हेल्पलाइन",
    footerHelplineNumber: "1930",
    footerHelplineDesc: "राष्ट्रीय साइबर अपराध हेल्पलाइन (टोल फ्री)",
    footerCitizenComplaints: "नागरिक शिकायतें: cybercrime.gov.in",
    footerAdvisoryNoticeTitle: "सलाहकारी सूचना:",
    footerAdvisoryNoticeBody: "ट्रेसएक्स अधिकृत अधिकारियों के लिए एक खोजी निर्णय-समर्थन प्रणाली है। जोखिम रेटिंग, सहसंबंध स्कोर और एआई-जनरेटेड विवरण केवल सलाहकार प्रकृति के हैं और किसी भी कानूनी कार्रवाई से पूर्व जाँच अधिकारी द्वारा इनका सत्यापन अनिवार्य है। पहुँच प्रतिबंधित, लॉग व निरंतर मॉनिटर की जाती है; अनधिकृत पहुँच अथवा दुरुपयोग लागू कानून के अंतर्गत दंडनीय है।",
    footerCopyright: "© {year} ट्रेसएक्स (TraceX). सर्वाधिकार सुरक्षित।",
    footerBackToTop: "शीर्ष पर वापस जाएँ",

    // ── AI Chatbot ───────────────────────────────────────────────────────
    chatLauncherTitle: "ट्रेसएक्स साइबर एआई सहायक खोलें",
    chatLauncherBrand: "ट्रेसएक्स साइबर एआई",
    chatLauncherGlobal: "ग्लोबल इंटेलिजेंस",
    chatLauncherLive: "लाइव",
    chatWindowTitle: "ट्रेसएक्स एआई सहायक",
    chatOnline: "ऑनलाइन",
    chatActiveContext: "सक्रिय संदर्भ: {caseLabel}",
    chatGlobalContext: "ग्लोबल थ्रेट इंटेलिजेंस नेटवर्क",
    chatClearTitle: "बातचीत साफ़ करें",
    chatClearBtn: "साफ़ करें",
    chatRestoreWidth: "सामान्य चौड़ाई पुनर्स्थापित करें",
    chatExpandWidth: "विंडो का विस्तार करें",
    chatCloseTitle: "विंडो बंद करें (Escape)",
    chatSuggestedPrefix: "सुझाव:",
    chatOfficerSender: "जाँच अधिकारी",
    chatModelSender: "ट्रेसएक्स इंटेलिजेंस मॉडल",
    chatCopyTitle: "संदेश कॉपी करें",
    chatNextActions: "अगली अनुशंसित कार्रवाइयां:",
    chatAnalyzingIndicator: "इंटेलिजेंस डेटाबेस, म्यूल ग्राफ़ एवं दूरसंचार रिकॉर्ड का विश्लेषण किया जा रहा है...",
    chatPlaceholderCase: "{caseLabel} के संबंध में ट्रेसएक्स एआई से पूछें...",
    chatPlaceholderGlobal: "उच्च-जोखिम संस्थाओं, धोखाधड़ी समूहों या कानूनी नोटिस के बारे में पूछें...",
    chatSendTitle: "प्रश्न भेजें",
    chatSecurityFooter: "इंटेलिजेंस इंजन v2.4 • शुरू से अंत तक एन्क्रिप्टेड",
    chatEscHint: "विंडो बंद करने के लिए Esc दबाएं",
    chatWelcomeMessage: "नमस्ते अधिकारी महोदय। मैं आपका ट्रेसएक्स साइबर इंटेलिजेंस सहायक हूँ। मुझसे सक्रिय प्रकरण जाँच, म्यूल खातों, एपीके थ्रेट सिगनेचर्स, या राज्य नेटवर्क में क्रॉस-केस फ्रॉड एनालिटिक्स के संबंध में कोई भी प्रश्न पूछें।",
    chatClearedMessage: "बातचीत इतिहास साफ़ कर दिया गया है। आज मैं आपकी जाँच में क्या सहायता कर सकता हूँ?",
    chatQuickPromptsCase: [
      "⚡ इस प्रकरण का सारांश दें",
      "🎯 उच्च-जोखिम वाली संस्थाओं की पहचान करें",
      "🏦 संदिग्ध म्यूल खातों का पता लगाएं",
      "🔗 क्रॉस-केस संबंध जांचें",
      "📜 अनुशंसित कानूनी फ़्रीज़ कार्रवाई",
    ],
    chatQuickPromptsGlobal: [
      "📊 कितने उच्च-जोखिम प्रकरण खुले हैं?",
      "🚨 सक्रिय जाँचों की सूची देखें",
      "📈 प्रमुख धोखाधड़ी ट्रेंड्स क्या हैं?",
      "🛡️ राज्य-स्तरीय म्यूल खातों का सारांश",
    ],

    // ── Network Graph Subtitle & Hop Controls ────────────────────────────
    graphTitle: "प्रकरण सहसंबंध ग्राफ़",
    graphSub: "संस्थाओं के बीच संबंधों का अन्वेषण करें। विवरण देखने के लिए किसी श्रेणी क्लस्टर पर क्लिक करें या ज़ूम करने के लिए Ctrl + स्क्रॉल करें।",
    graphHopOverview: "अवलोकन",
    graphHop1: "1 हॉप",
    graphHop2: "2 हॉप",
    graphHop3: "3 हॉप",

    // ── Domain Taxonomy Labels ───────────────────────────────────────────
    scams: {
      digital_scam: "डिजिटल धोखाधड़ी",
      phishing_vishing: "फ़िशिंग / विशिंग",
      malicious_apk: "दुर्भावनापूर्ण एपीके",
    },
    entities: {
      upi_handle: "यूपीआई हैंडल",
      account: "बैंक खाता",
      phone: "फ़ोन नंबर",
      imei: "आईएमईआई / डिवाइस",
      imsi: "सिम / आईएमएसआई",
      ip_address: "आईपी पता (IP)",
      apk_hash: "दुर्भावनापूर्ण एपीके",
      email: "ईमेल आईडी",
      url: "यूआरएल / वेबसाइट",
    },
    evidenceCategories: {
      telecom: "दूरसंचार साक्ष्य",
      bank_upi: "बैंक / यूपीआई",
      other: "अन्य आर्टिफ़ैक्ट्स",
    },
    statuses: {
      open: "खुला (Open)",
      correlating: "सहसंबंध जारी",
      under_review: "समीक्षाधीन",
      closed: "निस्तारित (Closed)",
    },
    evidenceStatuses: {
      queued: "कतारबद्ध",
      pending: "लंबित",
      processing: "प्रसंस्करण जारी",
      completed: "इंडेक्स किया गया",
      indexed: "इंडेक्स किया गया",
      error: "त्रुटि",
      failed: "विफल",
    },
    risks: {
      critical: "अति गंभीर",
      high: "उच्च",
      medium: "मध्यम",
      low: "निम्न",
      unrated: "अनिर्धारित",
    },
  },
};

export const t = (language) => STRINGS[language === "hi" ? "hi" : "en"] || STRINGS.en;
export const pick = (obj, language) => (obj && (obj[language === "hi" ? "hi" : "en"] || obj.en)) || "";

/** Localized domain taxonomy helper functions */
export const getScamLabel = (val, language) => {
  const dict = t(language).scams;
  return (dict && dict[val]) || val || "—";
};

export const getEntityTypeLabel = (val, language) => {
  const dict = t(language).entities;
  if (dict && dict[val]) return dict[val];
  return val ? String(val).replace(/_/g, " ") : (language === "hi" ? "संस्था" : "Entity");
};

export const getCaseStatusLabel = (val, language) => {
  const dict = t(language).statuses;
  return (dict && dict[val]) || val || "—";
};

export const getEvidenceCategoryLabel = (val, language) => {
  const dict = t(language).evidenceCategories;
  return (dict && dict[val]) || (val ? String(val).toUpperCase() : "—");
};

export const getEvidenceStatusLabel = (val, language) => {
  const dict = t(language).evidenceStatuses;
  return (dict && dict[val]) || val || "—";
};

export const getRiskLabel = (val, language) => {
  const dict = t(language).risks;
  const key = (val || "").toLowerCase();
  return (dict && dict[key]) || val || (language === "hi" ? "अनिर्धारित" : "Unrated");
};